name: Build Boost Libraries

on:
  workflow_dispatch:  # allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Boost code
      uses: actions/checkout@v3
      with:
        repository: boostorg/boost  # original Boost repository
        ref: boost-1.67.0  # specific tag
       # submodules: recursive  # gets Boost submodules

    - name: Set up Visual Studio
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 14.16  # Corresponds to Visual Studio 2017

    - name: Build Boost Libraries
      shell: cmd
      run: |
        cmd /c bootstrap
        cmd /c b2 toolset=msvc-14.1 address-model=64 variant=release link=shared runtime-link=shared

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: boost-binaries
        path: stage/lib/*  # Adjust this path based on where the built DLL and LIB files are located
