name: Build Boost Libraries

on:
  workflow_dispatch:  # allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Boost code
      uses: actions/checkout@v3
      with:
        repository: boostorg/boost  # original Boost repository
        ref: boost-1.67.0  # specific tag
        submodules: recursive  # gets Boost submodules



    - name: Set up Visual Studio
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 14.16  # Corresponds to Visual Studio 2017

    - name: Build Boost Libraries
      shell: cmd
      run: |
        cmd /c bootstrap
        b2 cxxflags="/Zc:inline /Zc:throwingNew" toolset=vc141 address-model=64 link=shared runtime-link=shared --with-chrono --with-date_time --with-filesystem --with-system --with-iostreams --with-locale --with-log --with-program_options --with-regex --with-serialization --with-thread --with-timer --with-test --with-serialization --with-python --with-fiber -q -a --debug-configuration toolset=msvc-14.1 variant=debug,release link=static,shared threading=multi runtime-link=shared define=BOOST_USE_WINAPI_VERSION=0x0A00

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: boost-binaries
        path: stage/lib/*  # Adjust this path based on where the built DLL and LIB files are located
